[build]
  command = "pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Static file handling
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Fallback for static assets
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = false


