[build]
  command = "pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure requests to /assets/* are served as static files without interference
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true


